# -*- coding: utf-8 -*-
"""TelegramBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15fOnMa5p6gDxE9nI65e6kC1hc_SRGAuj
"""

!pip install adafruit-io --quiet
!pip install python-telegram-bot==13.0

from Adafruit_IO import Client
aio = Client('Kingvishal1','aio_rREj25QdERrcybSlOtWCyipNn1H2')

from telegram.ext import Updater, CommandHandler,MessageHandler,Filters
def demo1(bot,update):
  chat_id = bot.message.chat_id
  path = 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fm.facebook.com%2Fokay.loja%2Fphotos%2F&psig=AOvVaw1PotWViF11J04dImPhX6Zg&ust=1626752686113000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMDz55Sc7vECFQAAAAAdAAAAABAD'
  bot.message.reply_text('I am okay.')
  update.bot.sendPhoto(chat_id=chat_id,photo=path)

def demo2(bot,update):
  bot.message.reply_text("My name is Vishal's_bot")

def lightOn(bot,update):
  chat_id = bot.message.chat_id
  aio.send('lightonoff', 1)
  path = 'https://i2.wp.com/business-ethics.com/wp-content/uploads/2011/09/EarthTalkBULB.jpg?zoom=1.25&resize=948%2C572&ssl=1'
  update.bot.sendPhoto(chat_id=chat_id,photo=path)
  bot.message.reply_text("light is turned on")

def lightOff(bot,update):
  chat_id = bot.message.chat_id
  aio.send('lightonoff', 0)
  path = 'https://media.istockphoto.com/photos/digital-illustration-of-electric-bulb-picture-id519960558?s=612x612'
  update.bot.sendPhoto(chat_id=chat_id,photo=path)
  bot.message.reply_text("light is turned off")

def fanOn(bot,update):
  chat_id = bot.message.chat_id
  aio.send('fanonoff', 1)
  path = 'https://www.thespruce.com/thmb/tyVxBz0q2ToJOLZCGKUHj6vwId0=/1883x1412/smart/filters:no_upscale()/GettyImages-182436453-5c79e51cc9e77c0001e98e6c.jpg'
  update.bot.sendPhoto(chat_id=chat_id,photo=path)
  bot.message.reply_text("fan is turned on")

def fanOff(bot,update):
  chat_id = bot.message.chat_id
  aio.send('fanonoff', 0)
  path = 'https://www.lifesavvy.com/p/uploads/2019/06/37df4c5d.jpg?height=200p&trim=2,2,2,2'
  update.bot.sendPhoto(chat_id=chat_id,photo=path)
  bot.message.reply_text("fan is turned off")

def main(bot,update):
  User_Input = bot.message.text.lower()
  print(User_Input)

  if User_Input== "how are you?":
    demo1(bot,update)
  elif User_Input=="what is your name?" or User_Input =="name please":
    demo2(bot,update)
  elif User_Input=="turn on the light" or User_Input=="light on":
    lightOn(bot,update)
  elif User_Input=="turn off the light" or User_Input=="light off":
    lightOff(bot,update)
  elif User_Input=="turn on the fan" or User_Input=="fan on":
    fanOn(bot,update)
  elif User_Input=="turn off the fan" or User_Input=="fan off":
    fanOff(bot,update)
  else:
    bot.message.reply_text('Invalid Text')

BOT_TOKEN = '1947365720:AAEM2adyhklP9id27IQcE70dIsQsh_RGEc8'
u = Updater(BOT_TOKEN,use_context=True)
dp = u.dispatcher
dp.add_handler(MessageHandler(Filters.text,main))
u.start_polling()
u.idle()

!pip install adafruit-io --quiet
!pip install python-telegram-bot==13.0

from Adafruit_IO import Client
aio = Client('Kingvishal1','aio_qunS98SL01wYgZaaTcNFZOyIYyKr')

aio.send('lightonoff', 1)
datUser_Input= aio.receive('lightonoff')
print(f'Received value: {data.value}')

aio.send('fanonoff', 1)
datUser_Input= aio.receive('fanonoff')
print(f'Received value: {data.value}')

!pip install adafruit-io --quiet
!pip install python-telegram-bot==13.0
